name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2

      -name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.6.3

      -name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      -name: Integration tests
        run: |
          python test/test.py

